export const defaultThemeSettings = [
  {
    id: 1,
    title: "titleBar",
    isOpen: false,
    data: [
      {
        id: 11,
        styleProp: "titleBar.activeBackground",
        value: "",
        label: "Background",
        cssVar: "--vscode-titleBar-activeBackground",
      },
      {
        id: 12,
        styleProp: "titleBar.activeForeground",
        value: "",
        label: "Text color",
        cssVar: "--vscode-titleBar-activeForeground",
      },
      {
        id: 13,
        styleProp: "titleBar.border",
        value: "",
        label: "Border",
        cssVar: "--vscode-titleBar-border",
      },
    ],
  },
  {
    id: 2,
    title: "activityBar",
    isOpen: false,
    data: [
      {
        id: 21,
        styleProp: "activityBar.foreground",
        value: "",
        label: "Icon color",
        cssVar: "--vscode-activityBar-foreground",
      },
      {
        id: 22,
        styleProp: "activityBar.inactiveForeground",
        value: "",
        label: "Inactive Icon color",
        cssVar: "--vscode-activityBar-inactiveForeground",
      },
      {
        id: 23,
        styleProp: "activityBar.background",
        value: "",
        label: "Background",
        cssVar: "--vscode-activityBar-background",
      },
      {
        id: 24,
        styleProp: "activityBar.activeBackground",
        value: "",
        label: "Active Background",
        cssVar: "--vscode-activityBar-activeBackground",
      },
      {
        id: 25,
        styleProp: "activityBar.border",
        value: "",
        label: "Border",
        cssVar: "--vscode-activityBar-border",
      },
      {
        id: 26,
        styleProp: "activityBar.activeBorder",
        value: "",
        label: "Active Border",
        cssVar: "--vscode-activityBar-activeBorder",
      },
    ],
  },
  {
    id: 3,
    title: "sideBar",
    isOpen: false,
    data: [
      {
        id: 31,
        styleProp: "sideBar.background",
        value: "",
        label: "Background",
        cssVar: "--vscode-sideBar-background",
      },
      {
        id: 32,
        styleProp: "sideBar.foreground",
        value: "",
        label: "Text color",
        cssVar: "--vscode-sideBar-foreground",
      },
      {
        id: 33,
        styleProp: "sideBarSectionHeader.background",
        value: "",
        label: "Header background",
        cssVar: "--vscode-sideBarSectionHeader-background",
      },
      {
        id: 34,
        styleProp: "sideBarSectionHeader.foreground",
        value: "",
        label: "Header Text color",
        cssVar: "--vscode-sideBarSectionHeader-foreground",
      },
      {
        id: 35,
        styleProp: "sideBar.border",
        value: "",
        label: "Border",
        cssVar: "--vscode-sideBar-border",
      },
      {
        id: 36,
        styleProp: "list.activeSelectionBackground",
        value: "",
        label: "Selected file Background",
        cssVar: "--vscode-list-activeSelectionBackground",
      },
      {
        id: 37,
        styleProp: "list.activeSelectionForeground",
        value: "",
        label: "Selected file color",
        cssVar: "--vscode-list-activeSelectionForeground",
      },
      // {
      //   id: 38,
      //   styleProp: "list.hoverBackground",
      //   value: "",
      //   label: "File hover background",
      // },
      // {
      //   id: 39,
      //   styleProp: "list.hoverForeground",
      //   value: "",
      //   label: "File hover color",
      // },
    ],
  },
  {
    id: 4,
    title: "statusBar",
    isOpen: false,
    data: [
      {
        id: 41,
        styleProp: "statusBar.foreground",
        value: "",
        label: "Text color",
        cssVar: "--vscode-statusBar-foreground",
      },
      {
        id: 42,
        styleProp: "statusBar.background",
        value: "",
        label: "Background",
        cssVar: "--vscode-statusBar-background",
      },
      {
        id: 43,
        styleProp: "statusBar.border",
        value: "",
        label: "Border",
        cssVar: "--vscode-statusBar-border",
      },
    ],
  },
  {
    id: 5,
    title: "terminal",
    isOpen: false,
    data: [
      // { id: 51, styleProp: "panel.background", value: "", label: "Background" },
      {
        id: 52,
        styleProp: "panel.border",
        value: "",
        label: "Border",
        cssVar: "--vscode-panel-border",
      },
      {
        id: 53,
        styleProp: "panelTitle.activeBorder",
        value: "",
        label: "Active title border",
        cssVar: "--vscode-panelTitle-activeBorder",
      },
      {
        id: 54,
        styleProp: "panelTitle.activeForeground",
        value: "",
        label: "Active title color",
        cssVar: "--vscode-panelTitle-activeForeground",
      },
      {
        id: 55,
        styleProp: "panelTitle.inactiveForeground",
        value: "",
        label: "Inactive title color",
        cssVar: "--vscode-panelTitle-inactiveForeground",
      },
      // {
      //   id: 56,
      //   styleProp: "terminal.selectionBackground",
      //   value: "",
      //   label: "Selected text background",
      // },
      {
        id: 57,
        styleProp: "terminalCursor.foreground",
        value: "",
        label: "Cursor color",
        cssVar: "--vscode-terminalCursor-foreground",
      },
      {
        id: 58,
        styleProp: "terminal.foreground",
        value: "",
        label: "Text color",
        cssVar: "--vscode-terminal-foreground",
      },
    ],
  },
  {
    id: 6,
    title: "editor",
    isOpen: false,
    data: [
      // {
      //   id: 61,
      //   styleProp: "editor.background",
      //   value: "",
      //   label: "Background",
      // }, ***
      {
        id: 62,
        styleProp: "editorLineNumber.foreground",
        value: "",
        label: "Line number color",
        cssVar: "--vscode-editorLineNumber-foreground",
      },
      {
        id: 63,
        styleProp: "editorCursor.foreground",
        value: "",
        label: "Cursor color",
        cssVar: "--vscode-editorCursor-foreground",
      },
      // {
      //   id: 64,
      //   styleProp: "editorError.foreground",
      //   value: "",
      //   label: "Error color",
      // },
      // {
      //   id: 65,
      //   styleProp: "editorWarning.foreground",
      //   value: "",
      //   label: "Warning color",
      // },
      // {
      //   id: 66,
      //   styleProp: "editorInfo.foreground",
      //   value: "",
      //   label: "Info color",
      // },
      // {
      //   id: 67,
      //   styleProp: "editor.selectionBackground",
      //   value: "",
      //   label: "Selected text background",
      // },
    ],
  },
];
