export const defaultThemeSettings = [
  {
    id: 1,
    title: "titleBar",
    isOpen: false,
    data: [
      {
        id: 11,
        styleProp: "titleBar.activeBackground",
        value: "",
        label: "Background",
      },
      {
        id: 12,
        styleProp: "titleBar.activeForeground",
        value: "",
        label: "Text color",
      },
      { id: 13, styleProp: "titleBar.border", value: "", label: "Border" },
    ],
  },
  {
    id: 2,
    title: "activityBar",
    isOpen: false,
    data: [
      {
        id: 21,
        styleProp: "activityBar.foreground",
        value: "",
        label: "Icon color",
      },
      {
        id: 22,
        styleProp: "activityBar.inactiveForeground",
        value: "",
        label: "Inactive Icon color",
      },
      {
        id: 23,
        styleProp: "activityBar.background",
        value: "",
        label: "Background",
      },
      {
        id: 24,
        styleProp: "activityBar.activeBackground",
        value: "",
        label: "Active Background",
      },
      { id: 25, styleProp: "activityBar.border", value: "", label: "Border" },
    ],
  },
  {
    id: 3,
    title: "sideBar",
    isOpen: false,
    data: [
      {
        id: 31,
        styleProp: "sideBar.background",
        value: "",
        label: "Background",
      },
      {
        id: 32,
        styleProp: "sideBar.foreground",
        value: "",
        label: "Text color",
      },
      {
        id: 33,
        styleProp: "sideBarSectionHeader.background",
        value: "",
        label: "Header background",
      },
      {
        id: 34,
        styleProp: "sideBarSectionHeader.foreground",
        value: "",
        label: "Header Text color",
      },
      { id: 35, styleProp: "sideBar.border", value: "", label: "Border" },
      {
        id: 36,
        styleProp: "list.activeSelectionBackground",
        value: "",
        label: "Active file Background",
      },
      {
        id: 37,
        styleProp: "list.activeSelectionForeground",
        value: "",
        label: "Active file color",
      },
      {
        id: 38,
        styleProp: "list.hoverBackground",
        value: "",
        label: "File hover background",
      },
      {
        id: 39,
        styleProp: "list.hoverForeground",
        value: "",
        label: "File hover color",
      },
    ],
  },
  {
    id: 4,
    title: "statusBar",
    isOpen: false,
    data: [
      {
        id: 41,
        styleProp: "statusBar.foreground",
        value: "",
        label: "Text color",
      },
      {
        id: 42,
        styleProp: "statusBar.background",
        value: "",
        label: "Background",
      },
      { id: 43, styleProp: "statusBar.border", value: "", label: "Border" },
    ],
  },
  {
    id: 5,
    title: "terminal",
    isOpen: false,
    data: [
      { id: 51, styleProp: "panel.background", value: "", label: "Background" },
      { id: 52, styleProp: "panel.border", value: "", label: "Border" },
      {
        id: 53,
        styleProp: "panelTitle.activeBorder",
        value: "",
        label: "Active title border",
      },
      {
        id: 54,
        styleProp: "panelTitle.activeForeground",
        value: "",
        label: "Active title color",
      },
      {
        id: 55,
        styleProp: "panelTitle.inactiveForeground",
        value: "",
        label: "Inactive title color",
      },
      {
        id: 56,
        styleProp: "terminal.selectionBackground",
        value: "",
        label: "Selected text background",
      },
      {
        id: 57,
        styleProp: "terminalCursor.foreground",
        value: "",
        label: "Cursor color",
      },
      {
        id: 58,
        styleProp: "terminal.foreground",
        value: "",
        label: "Text color",
      },
    ],
  },
  {
    id: 6,
    title: "editor",
    isOpen: false,
    data: [
      {
        id: 61,
        styleProp: "editor.background",
        value: "",
        label: "Background",
      },
      {
        id: 62,
        styleProp: "editorLineNumber.foreground",
        value: "",
        label: "Line number color",
      },
      {
        id: 63,
        styleProp: "editorCursor.foreground",
        value: "",
        label: "Cursor color",
      },
      {
        id: 64,
        styleProp: "editorError.foreground",
        value: "",
        label: "Error color",
      },
      {
        id: 65,
        styleProp: "editorWarning.foreground",
        value: "",
        label: "Warning color",
      },
      {
        id: 66,
        styleProp: "editorInfo.foreground",
        value: "",
        label: "Info color",
      },
      {
        id: 67,
        styleProp: "editor.selectionBackground",
        value: "",
        label: "Selected text background",
      },
    ],
  },
];
